-   id: rm_unneeded_f_str
    name: rm_unneeded_f_str
    description: 'Find and replace unneeded f-strings in your code.'
    entry: rm-unneeded-f-str
    language: python
    types: [python]
    require_serial: true
